#! /bin/sh

bspc rule -r "*"

pgrep -x picom > /dev/null || picom -b &
pgrep -x nitrogen > /dev/null || nitrogen --restore &
pgrep -x light-locker > /dev/null || light-locker --lock-on-suspend &
pgrep -x nm-applet > /dev/null || nm-applet &

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &
pgrep -x redshift > /dev/null || redshift &
pgrep -x mons > /dev/null || mons -a -x $HOME/.config/bspwm/scripts/generic-handler.sh &!
pgrep -x pulseaudio /dev/null || pulseaudio --start &

pgrep -x cleanfullscreen.sh > /dev/null || $HOME/.config/bspwm/scripts/cleanfullscreen.sh &

$HOME/.config/polybar/launch.sh

pgrep -x setxkbmap > /dev/null || setxkbmap -option 'caps:ctrl_modifier' &
pgrep -x xcape > /dev/null || xcape -e 'Caps_Lock=Escape' &

###---MONITORS---###
bspc monitor eDP1 -d 1 2 3
bspc monitor HDMI1 -d 4 5 6
bspc monitor DP1 -d 7 8 9

###---Global Settings---###
bspc config focus_follows_pointer true

bspc config normal_border_color	"4c566a"
bspc config focused_border_color "#406ea5"

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
bspc rule -a Zathura state=floating
#bspc rule -a Screenkey manage=off
#bspc rule -a pavucontrol state=floating

