#! /bin/sh

bspc rule -r "*"

pgrep -x setxkbmap > /dev/null || setxkbmap -option 'caps:ctrl_modifier'
pgrep -x xcape > /dev/null || xcape -e 'Caps_Lock=Escape'
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x nitrogen > /dev/null || nitrogen --restore
pgrep -x dunst > /dev/null || dunst &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &
pgrep -x light-locker > /dev/null || light-locker --lock-on-suspend &
pgrep -x redshift > /dev/null || redshift &
pgrep -x pulseaudio > /dev/null || pulseaudio &
pgrep -x spotifyd > /dev/null || spotifyd &

###---MONITORS---###
bspc monitor -d 1 2 3 4 5 6 7

###---Global Settings---###
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config focused_border_color "#406ea5"

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
#bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above
bspc rule -a Zathura state=floating
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
